spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/app_modernization
  profiles:
    active: default
  mail:
    host: smtp.office365.com
    port: 587
    username: Hr.policies@bilvantis.io
    password: WLZCMgQinKuthL8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: 8081